/** Glosario: métricas de entrenamiento y rendimiento. */
import { GLOSSARY_HEALTH, type GlossaryEntry } from "./glossary-health";

const GLOSSARY_TRAINING: Record<string, GlossaryEntry> = {
  esfuerzo: { t: "Esfuerzo (0–21)", what: "La carga que soportó tu sistema cardiovascular en el día: minutos en cada zona de pulso de tus entrenamientos más tu actividad diaria.", why: "Ayuda a dosificar: el esfuerzo ideal depende de lo recuperado que estés.", ref: "Ligero < 10 · Moderado 10–13 · Alto 14–17 · Máximo ≥ 18. La escala es logarítmica: cada punto arriba cuesta más.", tip: "Mira el objetivo de esfuerzo del día (según tu recuperación) y trata de quedarte dentro." },
  vo2max: { t: "VO2 máx.", what: "El máximo de oxígeno que tu cuerpo puede usar por minuto y kilo. Es el tamaño de tu motor aeróbico.", why: "Es uno de los predictores más potentes de longevidad y salud cardiovascular, y define tu techo de rendimiento.", ref: "Depende de edad y sexo; mira tu categoría en la sección Salud.", tip: "Mejora con series de 3–5 min a ritmo fuerte y con volumen aeróbico constante." },
  fitness_age: { t: "Edad física", what: "La edad que corresponde a tu VO2 máx., pulso en reposo, IMC y actividad.", why: "Una forma intuitiva de ver si tu cuerpo funciona como el de alguien más joven o mayor.", ref: "Por debajo de tu edad real = buena señal.", tip: "Sube la actividad vigorosa semanal y mejora el peso corporal." },
  training_status: { t: "Estado de entrenamiento", what: "Cómo evoluciona tu forma física según tu carga y tu VO2 máx.: productivo, mantenimiento, recuperación, pico, sobrecarga, no productivo o pérdida de forma.", why: "Te dice si tu entrenamiento está funcionando.", ref: "Lo ideal es alternar Productivo y Mantenimiento, con algo de Recuperación.", tip: "«No productivo» suele significar que la carga está bien pero no recuperas: revisa el sueño y el estrés." },
  acwr: { t: "Carga aguda vs crónica (ACWR)", what: "Compara tu carga de los últimos 7 días (aguda) con la de las últimas 4 semanas (crónica, a lo que tu cuerpo está acostumbrado).", why: "Subir la carga más rápido de lo que te adaptas es la primera causa de lesiones.", ref: "0,8–1,3 zona óptima · 1,3–1,5 precaución · > 1,5 alto riesgo de lesión.", tip: "Sube el volumen como máximo un 10–20 % por semana y haz una semana de descarga cada 3–4." },
  load_focus: { t: "Enfoque de carga", what: "Cómo se reparte tu carga de 4 semanas entre aeróbico bajo (suave), aeróbico alto (umbral/tempo) y anaeróbico (series muy intensas).", why: "Un buen entrenamiento necesita las tres, en proporción a tu objetivo.", ref: "El recuadro marca el rango objetivo de Garmin para cada una.", tip: "Si falta aeróbico bajo: más rodajes suaves. Si falta anaeróbico: series cortas." },
  race: { t: "Predicciones de carrera", what: "Tiempo estimado por Garmin para 5 K, 10 K, media y maratón, basado en tu VO2 máx. y tu historial.", why: "Sirve para elegir objetivos realistas y ritmos de entrenamiento.", ref: "En distancias largas asumen que has hecho tiradas largas suficientes.", tip: "Si tu objetivo es más rápido que la predicción, el plan del entrenador te dirá cuánto falta." },
  endurance: { t: "Puntuación de resistencia", what: "Tu capacidad de sostener esfuerzos largos, combinando VO2 máx. y carga de entrenamiento de todos tus deportes.", why: "Complementa al VO2 máx.: mide aguante, no solo motor.", ref: "Categorías de Recreativo a Élite.", tip: "Sube con sesiones largas y constancia semanal." },
  lactate: { t: "Umbral de lactato", what: "El pulso y ritmo a partir de los cuales el lactato se acumula más rápido de lo que lo eliminas. Es el esfuerzo que puedes sostener ~1 hora.", why: "Es la mejor referencia para fijar tus zonas de entrenamiento personales.", ref: "Garmin lo detecta con banda de pecho en carreras con esfuerzos sostenidos.", tip: "Haz la prueba guiada del reloj cada 6–8 semanas." },
  zones: { t: "Zonas de frecuencia cardiaca", what: "Rangos de pulso que corresponden a intensidades: Z1 muy suave, Z2 aeróbico, Z3 tempo, Z4 umbral, Z5 máximo.", why: "Cada zona entrena algo distinto. Los mejores resultados llegan con ~80 % del tiempo en Z1–Z2 y ~20 % en Z4–Z5.", ref: "Evita pasar demasiado tiempo en Z3: cansa bastante y aporta poco.", tip: "Configura las zonas por FC umbral en el reloj para mayor precisión." },
  decoupling: { t: "Desacople aeróbico (Pa:HR)", what: "Compara la relación entre ritmo (o potencia) y pulso en la primera y la segunda mitad de una sesión continua.", why: "Si el pulso sube mientras el ritmo se mantiene, tu base aeróbica todavía no aguanta esa duración. Es una de las métricas favoritas de los entrenadores de resistencia.", ref: "< 5 % excelente base aeróbica · 5–10 % aceptable · > 10 % la duración supera tu base (o hubo calor o deshidratación). Solo tiene sentido en sesiones continuas de ≥ 40 min.", tip: "Más volumen en zona 2, salir más lento al principio e hidratarte en sesiones largas." },
};

export const GLOSSARY: Record<string, GlossaryEntry> = { ...GLOSSARY_HEALTH, ...GLOSSARY_TRAINING };
export type GlossaryKey = keyof typeof GLOSSARY;
