/** Glosario: métricas de salud, sueño y recuperación. */
export interface GlossaryEntry { t: string; what: string; why: string; ref: string; tip: string }

export const GLOSSARY_HEALTH: Record<string, GlossaryEntry> = {
  recuperacion: { t: "Recuperación (0–100 %)", what: "Cuánto se ha recuperado tu cuerpo, calculado con tu VFC nocturna, tu pulso en reposo y tu sueño frente a tus propios valores de los últimos 30 días.", why: "Te dice si hoy conviene exigirse o bajar el ritmo. Entrenar duro con la recuperación baja da menos beneficio y más riesgo de lesión.", ref: "Verde ≥ 67 · Amarillo 34–66 · Rojo ≤ 33.", tip: "Sube con sueño suficiente y regular, menos alcohol, buena hidratación y días suaves tras los duros." },
  sueno_rend: { t: "Rendimiento del sueño", what: "El porcentaje del sueño que necesitabas que realmente dormiste.", why: "La necesidad cambia cada día: aumenta con el esfuerzo del día anterior y con la deuda de sueño acumulada.", ref: "≥ 85 % óptimo · 70–84 % suficiente · < 70 % insuficiente.", tip: "Si sabes que mañana necesitas más sueño, adelanta la hora de acostarte en lugar de retrasar la alarma." },
  readiness: { t: "Disposición para entrenar (Garmin)", what: "Puntuación de 0 a 100 que combina seis factores: sueño de anoche, historial de sueño, tiempo de recuperación, carga aguda, VFC e historial de estrés.", why: "Es la recomendación de Garmin sobre cuánto exigirte hoy.", ref: "Óptima 95–100 · Alta 75–94 · Moderada 50–74 · Baja 25–49 · Muy baja < 25.", tip: "Revisa qué factor está más bajo en la sección Recuperación: te dice qué mejorar." },
  body_battery: { t: "Body Battery", what: "Tu nivel de energía de 5 a 100, como la batería de un móvil. Lo carga el descanso (sobre todo dormir) y lo gastan el ejercicio, el estrés y la actividad.", why: "Te ayuda a planificar el día y a ver qué te agota.", ref: "Al despertar lo ideal es > 70. Por debajo de 25 conviene descansar.", tip: "Siestas cortas, pausas sin pantalla y cenar ligero ayudan a cargarla." },
  sleep_score: { t: "Puntuación de sueño (Garmin)", what: "Nota de 0 a 100 que valora la duración, las fases (profundo, ligero, REM), los despertares y el estrés durante la noche.", why: "Resume la calidad de tu descanso.", ref: "Excelente 90–100 · Buena 80–89 · Aceptable 60–79 · Deficiente < 60.", tip: "Habitación fresca (18–20 °C) y oscura, sin alcohol ni pantallas antes de dormir, y horarios fijos." },
  hrv: { t: "Variabilidad de la frecuencia cardiaca (VFC/HRV)", what: "Las pequeñas variaciones de tiempo entre un latido y el siguiente, medidas mientras duermes (en milisegundos).", why: "Una VFC alta respecto a tu normal indica un sistema nervioso relajado y recuperado; una VFC baja, estrés, fatiga o enfermedad. Es de los mejores indicadores de recuperación.", ref: "Es muy individual: compárala solo con tu propia línea base. Garmin la marca como Equilibrada cuando tu media de 7 días está en tu rango.", tip: "Sube con sueño regular, ejercicio aeróbico, respiración lenta y menos alcohol." },
  rhr: { t: "Frecuencia cardiaca en reposo", what: "Tus pulsaciones por minuto en total reposo, normalmente durante el sueño.", why: "Un corazón entrenado late menos en reposo. Si sube varios latidos sobre tu normal, suele indicar fatiga, estrés, deshidratación o el inicio de una enfermedad.", ref: "Adultos 60–80 ppm; deportistas 40–60. Más de 80 de forma sostenida se asocia a más riesgo cardiovascular.", tip: "Baja con entrenamiento aeróbico regular y buen descanso." },
  stress: { t: "Estrés (Garmin)", what: "Nivel de 0 a 100 estimado a partir de tu VFC durante el día cuando estás quieto.", why: "Refleja la carga del sistema nervioso: trabajo, preocupaciones, cafeína, falta de sueño o digestión.", ref: "0–25 reposo · 26–50 bajo · 51–75 medio · 76–100 alto.", tip: "2–5 minutos de respiración lenta (actividad Respiración del reloj) bajan el estrés al momento." },
  steps: { t: "Pasos", what: "Pasos diarios contados por el acelerómetro del reloj.", why: "El movimiento diario, además del entrenamiento, reduce el riesgo cardiovascular y metabólico.", ref: "El beneficio para la salud crece claramente hasta ~8.000–10.000 pasos al día.", tip: "Llamadas caminando, escaleras y bajarte una parada antes suman rápido." },
  intensity: { t: "Minutos de intensidad", what: "Minutos de actividad moderada (cuentan x1) o vigorosa (x2), como recomienda la OMS.", why: "Es la métrica con más evidencia en salud: 150 minutos a la semana reducen la mortalidad de forma notable.", ref: "OMS: 150–300 min moderados o 75–150 vigorosos por semana.", tip: "Reparte a lo largo de la semana; bloques de 10 minutos ya cuentan." },
  spo2: { t: "Saturación de oxígeno (SpO₂)", what: "El porcentaje de oxígeno en tu sangre, medido de noche con luz en la muñeca.", why: "Caídas repetidas por debajo del 88–90 % pueden indicar apnea del sueño. También te dice cómo te aclimatas a la altitud.", ref: "Normal 95–100 % a nivel del mar; algo menos en altura.", tip: "Actívalo solo durante el sueño para ahorrar batería. Si ves caídas frecuentes, revisa la sección Salud." },
  sleep_stages: { t: "Fases del sueño", what: "Ligero (transición), profundo (reparación física y del sistema inmune) y REM (memoria, aprendizaje y emociones). Se repiten en ciclos de ~90 min.", why: "Cada fase cumple una función: el profundo domina al inicio de la noche y el REM al final.", ref: "Profundo 13–23 % · REM 20–25 % · Ligero ~50–60 %.", tip: "El alcohol reduce el REM; las cenas copiosas y el calor reducen el profundo." },
  le8: { t: "Salud cardiovascular (Life's Essential 8)", what: "Índice de 0 a 100 de la American Heart Association con 8 factores: actividad, sueño, peso, presión, tabaco, colesterol, glucosa y alimentación.", why: "Cada 10 puntos más se asocian a menos infartos, ACV y demencia.", ref: "Alta ≥ 80 · Moderada 50–79 · Baja < 50.", tip: "El reloj mide 3 factores; completa el resto en tu Perfil para un cálculo completo." },
};
